version: "3.8"

services:
  redis:
    image: redis:6.2.5
    container_name: wgra_redis
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 3606:6379

  mongodb:
    image: mongo:5.0.1
    container_name: wgra_mongodb
    restart: unless-stopped
    logging:
      driver: none
    env_file:
      - .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo_volume:/db/data
    ports:
      - 3605:27017

volumes:
  mongo_volume:
