version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: wgra_redis
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - 3606:6379

  mongodb:
    image: mongo:latest
    container_name: wgra_mongodb
    restart: always
    env_file:
      - .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo_volume:/db/data
    ports:
      - 3605:27017

  scraper:
    image: keimeno/wgra-scraper:latest
    volumes:
      - ./.env:/usr/src/scraper/.env
      - ./.scraper.env:/usr/src/scraper/packages/scraper/.env
    restart: always

volumes:
  mongo_volume:
